<a href="https://colab.research.google.com/github/Ranniellsaur/Linear-Algebra-58019/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and Its Operations

In [2]:
import numpy as np
#Create a NumPy program that performs the operations of the given matrices:

# sum = A +B
# difference1 = A - B
# difference2 = B - B

A = np.array([-5,0,4,1])
B = np.array([6,-3,2,3])

sum = A + B
print(sum)

difference1 = A - B
print(difference1)

difference2 = B - B
print(difference2)

[ 1 -3  6  4]
[-11   3   2  -2]
[0 0 0 0]
